Rename q35_sea to q35_sea_bios
oVirt/ovirt-ansible-collection pull request #111
Opened 2020-09-08 17:01 UTC by ahadas

To be aligned with the oVirt's API

Signed-off-by: Arik Hadas <ahadas@redhat.com>

2020-09-08 17:05 UTC, ahadas commented
@arachmani  @oliel could you please review this?

2020-09-09 07:29 UTC, mnecas requested changes
Looks great!
Could you just please add the changelog?
https://github.com/oVirt/ovirt-ansible-collection/tree/master/changelogs

2020-09-09 07:41 UTC, ahadas commented
@mnecas done - please feel free to modify it in case I didn't add it correctly

2020-09-09 07:54 UTC, mnecas approved these changes

2020-09-09 07:54 UTC, merged