add ovirt_repositories_disable_gpg_check to repositories param
oVirt/ovirt-ansible-collection pull request #167
Opened 2020-10-29 12:16 UTC by kobihk

disable_gpg_check was limited to the following condition:
if 'master.rpm' in ovirt_repositories_ovirt_release_rpm

2020-10-29 12:16 UTC, ovirt-infra commented
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

2020-10-29 12:17 UTC, kobihk commented
@mwperina @mnecas could you please CR

2020-10-29 19:25 UTC, mnecas requested changes
The patch would not work by default with master rpm, it would try to check the gpg and it would fail because they are not signed.
Maybe don't define the variable and then if it is defined by user use it, else the logic before.

2020-10-30 13:29 UTC, mnecas approved these changes
LGTM

2020-11-02 08:51 UTC, mwperina approved these changes
+1

2020-11-02 08:51 UTC, merged