ovirt_disk: fix transfer ending
oVirt/ovirt-ansible-collection pull request #215
Opened 2021-02-01 18:13 UTC by mnecas

Issue: when uploading the image there was sometime a delay, but the status of the disk was OK so it tried to attach the disk to the VM at that moment it failed because of the unfinished transfer status.

Now we wait longer after the transfer is done and it is removed.

I think it would be best to fix this in the SDK and this could be just a temporary fix.

2021-02-02 12:46 UTC, mnecas commented
@mwperina @nirs

2021-02-03 06:15 UTC, mwperina commented
SDK is generated automatically, why should we fixed something here? If something needs to be fixed, then it should be fixed in RESTAPI and/or engine backend no?

@barpavel

2021-02-03 06:24 UTC, mwperina requested changes
-1 until we finalize discussion in https://bugzilla.redhat.com/show_bug.cgi?id=1883949

2021-02-04 13:57 UTC, barpavel commented on plugins/modules/ovirt_disk.py
> +            try:
Looks like the code is indented to the right 1 tab too much?
Lines:
465-469
476-478

2021-02-04 14:03 UTC, barpavel commented
> SDK is generated automatically, why should we fixed something here? If something needs to be fixed, then it should be fixed in RESTAPI and/or engine backend no?

Sounds reasonable. But I prefer to hear @nirs opinion as well.

2021-02-18 10:08 UTC, mnecas commented
We have decided to wait for a fix from the storage team in https://bugzilla.redhat.com/show_bug.cgi?id=1849861

2021-02-18 10:08 UTC, closed without merging