manageiq: deprecate role
oVirt/ovirt-ansible-collection pull request #375
Opened 2021-11-05 12:44 UTC by mnecas

We have decided to no longer support the `manageiq` role, for this reason we are deprecating it.

2021-11-05 13:18 UTC, mwperina requested changes

2021-11-05 13:18 UTC, mwperina commented on changelogs/fragments/375-manageiq-deprecate.yml
> +  - manageiq - role deprecated (https://github.com/oVirt/ovirt-ansible-collection/pull/375).
role removed?

2021-11-15 08:48 UTC, mwperina approved these changes
PR title is misleading, but other than that looks OK

2021-11-15 09:25 UTC, mnecas commented
ci test please

2021-11-22 17:23 UTC, mwperina requested changes

2021-11-22 17:23 UTC, mwperina commented on ovirt-ansible-collection.spec.in
> -Obsoletes:	ovirt-ansible-manageiq
Hmm I'd leave it here in case anyone upgrade from very ancient setup to the latest ovirt-ansible-collection

2021-11-22 17:23 UTC, mwperina commented on ovirt-ansible-collection.spec.in
> -Provides:	ovirt-ansible-manageiq
Same as above

2021-11-24 13:35 UTC, mwperina approved these changes
+1

2021-11-29 12:52 UTC, merged