automation: fix ansible requirement for centos9-stream
oVirt/ovirt-ansible-collection pull request #388
Opened 2021-11-22 15:46 UTC by mnecas

2021-11-22 17:18 UTC, mwperina requested changes

2021-11-22 17:18 UTC, mwperina commented on ovirt-ansible-collection.spec.in
> +Requires:	ansible >= 2.11
Shouldn't it be ansible-core?
```
Requires:	ansible-core >= 2.11.0
```

2021-11-24 13:36 UTC, mwperina approved these changes
+1

2021-11-24 14:15 UTC, sandrobonazzola approved these changes
lgtm

2021-11-25 15:54 UTC, merged