ovirt_remove_stale_lun: Use add_host instead of delegate_to
oVirt/ovirt-ansible-collection pull request #390
Opened 2021-11-24 13:20 UTC by nijinashok

As of now, we are using delegate_to using with_items to run the tasks in multiple hosts. This has got several problems:

- Ansible considers tasks for all the hosts as single task since we are iterating over host_info using with_items to run it on multiple hosts. So if any of the tasks fails in any of the hosts, it stops the execution of the subsequent tasks on all other hosts. For example, if multipath -f fails on any hosts, it won't run the task for removing the SCSI device even for the hosts where it was able to remove the device from multipath successfully.

- Each task is executed serially on the discovered hosts in DC because with_items unpacks serially.

- It's very difficult to understand which host it got failed, and "PLAY RECAP" is not useful.

Using add_host automatically solves the above problems.

2021-11-24 13:20 UTC, ovirt-infra commented
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

2021-11-24 13:34 UTC, mwperina commented
ci add to whitelist

2021-11-24 20:52 UTC, vjuranek approved these changes
Nice, definitely more efficient and nicer solution! LGTM, it doesn't change functionality what it does on hosts, this is mainly Ansible related change. That being said, Martin's review is much more relevant here than mine.

2021-11-26 11:34 UTC, mnecas requested changes

2021-11-29 03:06 UTC, nijinashok commented on roles/remove_stale_lun/examples/remove_stale_lun.yml
> +    - {'role': 'remove_stale_lun', 'fetch_hosts': false}
Done

2021-11-29 03:06 UTC, nijinashok commented on roles/remove_stale_lun/examples/remove_stale_lun.yml
> +    - {'role': 'remove_stale_lun', 'fetch_hosts': true}
Done.

2021-11-29 12:07 UTC, mnecas approved these changes
LGTM

2021-11-29 12:07 UTC, merged