Add CODEOWNERS
oVirt/ovirt-ansible-collection pull request #419
Opened 2022-01-24 16:22 UTC by mnecas

https://help.github.com/en/articles/about-code-owners

2022-01-24 17:22 UTC, mwperina requested changes

2022-01-24 17:22 UTC, mwperina commented on .github/CODEOWNERS
> +* @mnecas @arachmani @barpavel
Please fill-in codeowners file according to current responsibilities. For example you can take a look to VDSM: https://github.com/oVirt/vdsm/blob/master/CODEOWNERS
Each of current maintaners already have his own field of responsoibility

2022-01-25 08:19 UTC, mwperina approved these changes
+1

2022-01-25 12:08 UTC, vjuranek approved these changes

2022-01-25 12:36 UTC, barpavel approved these changes

2022-01-25 12:55 UTC, merged