ovirt_qos, ovirt_disk_profile, ovirt_disk: Add modules to allow for creation and updating of disk_profiles
oVirt/ovirt-ansible-collection pull request #422
Opened 2022-01-26 17:34 UTC by odonnelln

Summary

- Adds ovirt_qos module to create a new QoS entry
- Adds ovirt_disk_profile to create a new disk profile
- Updates ovirt_disk to allow you to define the disk_profile on creation or to update a disk that currently exists

Examples
```yaml
  ovirt.ovirt.ovirt_qos:
    auth: "{{ ovirt_auth }}"
    name: "myqos"
    data_center: "Default"
    state: "present"
    max_iops: "100"
    max_throughput: "100"
    type: "storage"

  ovirt.ovirt.ovirt_disk_profile:
    auth: "{{ ovirt_auth }}"
    name: "mydisk"
    data_center: "Default"
    state: "present"
    storage_domain: "mystoragedomain"
    qos: "myqos"

  ovirt.ovirt.ovirt_disk:
    auth: "{{ ovirt_auth }}"
    name: "mydisk"
    profile: "myqos"
    state: "present"

```

2022-01-27 11:58 UTC, mnecas requested changes
Hi @odonnelln, thanks for the PR great work! I have just some nits, quite a lot of them are repetitive because of the amount of added code, and a lot of them are from the CI. Please don't hesitate to ping me.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +short_description: "Module to manage storage domain disk profiles in oVirt/RHV"
Please remove the `/RHV` or replace the `oVirt/RHV` with `@NAME@`.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +    - "Module to manage storage domain disk profiles in oVirt/RHV."
Please remove the `/RHV` or replace the `oVirt/RHV` with `@NAME@`.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +            - "Name of the QoS entry on the disk profile. If not passed defaults to oVirt/RHV HE default"
Please remove the `/RHV` or replace the `oVirt/RHV` with `@NAME@`.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +short_description: "Module to manage QoS entries in oVirt/RHV"
Please remove the `/RHV` or replace the `oVirt/RHV` with `@NAME@`.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +    - "Module to manage QoS entries in oVirt/RHV."
Please remove the `/RHV` or replace the `oVirt/RHV` with `@NAME@`.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +    description: "Dictionary of all the QoS attributes. QoS attributes can be found on your oVirt/RHV instance
Please remove the `/RHV` or replace the `oVirt/RHV` with `@NAME@`.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +    description: "Dictionary of all the disk profile attributes. Disk profile attributes can be found on your oVirt/RHV instance
Please remove the `/RHV` or replace the `oVirt/RHV` with `@NAME@`.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +        write_throughput=dict(default=None),
Please remove these lines the documentation is not compiled properly because of it.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +    type: "storage"
Please add the prefix `@NAMESPACE@.@NAME@` to the `ovirt_qos` name.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +            return None
Please remove the `else` and just leave `return None`.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +            return None
Please raise the exception that the Datacenter was not found.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +class DiskProfileModule(BaseModule):
Please add an extra line.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +    def build_entity(self):
Please remove the extra line.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +def main():
Please remove the extra 2 lines.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +if __name__ == "__main__":
Please add an extra line.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +
remove the blank line at end of file

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +
remove the blank line at end of file

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +if __name__ == "__main__":
Please add an extra line.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +            ['max_iops','read_iops'],
Add whitespace after ,

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +            ['max_throughput', 'write_througput']
Add whitespace after `,`

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +class QosModule(BaseModule):
Please add an extra line.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +def _get_qoss_service(connection, dc_name):
Please add an extra line.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +def main():
Please remove the extra line.

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +#!/usr/bin/python
Add please to the shebang  license.
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2022 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
```

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +#!/usr/bin/python
Please add license
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2022 Red Hat, Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
```

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +        type: str
Shouldn't these be integers?

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +    dc_service = dcs_service.data_center_service(dc.id)
Maybe could be replace with
```python
dcs_service = connection.system_service().data_centers_service()
return dcs_service.data_center_service(get_id_by_name(dcs_service, dc_name)).qoss_service()
```

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +        return storage_domain
Maybe could be replaced by `get_id_by_name` as in comment on QoS

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +        return qos
Maybe could be replaced by `get_id_by_name` as in comment on QoS

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk_profile.py
> +            name=self._module.params.get('id') if self._module.params.get('id') else self._module.params.get('name'),
The DIskProfile has the id and name. Please change the code to 
```python
name=self._module.params.get('id') if self._module.params.get('name') else None,
id = self._module.params.get('id') if self._module.params.get('id') else None
 ```

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_qos.py
> +            name=self._module.params.get('id') if self._module.params.get('id') else self._module.params.get('name'),
The Qos has the id and name. Please change the code to 
```python
name=self._module.params.get('id') if self._module.params.get('name') else None,
id = self._module.params.get('id') if self._module.params.get('id') else None
 ```

2022-01-27 11:58 UTC, mnecas commented on plugins/modules/ovirt_disk.py
> +        return changed
Is it necessary to have a separate method for an update of the disk profiles?
I think it should go to the `update_check`
https://github.com/oVirt/ovirt-ansible-collection/blob/master/plugins/modules/ovirt_disk.py#L719

2022-02-16 12:41 UTC, mwperina commented
Hi Niall,

Thanks a lot for contribution. Your patch looks good, but need a bit more work. Could you please take a look at comments?

Thanks,
Martin

2022-02-28 15:58 UTC, odonnelln commented
@mnecas Sorry for the delay in getting back to this. I have addressed all your comments. Not sure what process is here for resolving comments, in my work we leave it to the person who adds the comment to resolve but please let me know if you want me to resolve them all.

2022-06-14 07:50 UTC, mnecas approved these changes

2022-06-14 07:54 UTC, mnecas commented
@odonnelln once again great job and thank you for you PR!
I added QoS params for network, hostnetwork, cpu, and some details.

2022-06-14 07:54 UTC, merged