cluster_upgrade: Directly log progress to the cluster
oVirt/ovirt-ansible-collection pull request #449
Opened 2022-03-18 16:44 UTC by sjd78

When running against a ovirt 4.5 instance, use the new REST feature
defined by [1] and [2] to report the progress by both logging events
and pushing the progress to the cluster.

[1]: https://github.com/oVirt/ovirt-engine-api-model/pull/32
[2]: https://github.com/oVirt/ovirt-engine/pull/170
Bug-Url: https://bugzilla.redhat.com/2040474

2022-03-23 16:27 UTC, sgratch approved these changes

2022-03-24 13:49 UTC, sjd78 commented
Note: Updated now that https://github.com/oVirt/ovirt-engine-api-model/pull/32 has been merged and the REST service parameters are set properly.

2022-03-24 16:47 UTC, mnecas requested changes
Please add the changelog

2022-03-24 17:07 UTC, mnecas approved these changes
LGTM

2022-03-24 18:52 UTC, merged

2022-03-24 20:34 UTC, mwperina commented
> Note: Updated now that [oVirt/ovirt-engine-api-model#32](https://github.com/oVirt/ovirt-engine-api-model/pull/32) has been merged and the REST service parameters are set properly.

Not really, this will not work until api-model is bumped in the engine

2022-03-24 22:15 UTC, sjd78 commented
> > Note: Updated now that [oVirt/ovirt-engine-api-model#32](https://github.com/oVirt/ovirt-engine-api-model/pull/32) has been merged and the REST service parameters are set properly.
> 
> Not really, this will not work until api-model is bumped in the engine

Good point.

Really I just meant that the parameter names would not be changing so the code here will not need to be changed again.