he-setup: ovn should be configured with he_ansible_host_name
oVirt/ovirt-ansible-collection pull request #568
Opened 2022-07-31 11:01 UTC by erav

The FQDN of the HE host is returned by the variable he_ansible_host_name
and not by he_host_name.
This commit fixes commit 7ed85c7862fdb0f7ed7e5f61c771e85dc1774bbb,
(change-id I951f90a9bb035d52285a8c5800f4711aecf34ab6).

Change-Id: I22d97c869ffd0e05be652eb59b11b5e05db24b21

Signed-off-by: Eitan Raviv <eraviv@redhat.com>

2022-07-31 11:13 UTC, erav commented
/ost he-basic-suite-master

2022-07-31 12:47 UTC, erav commented
/ost he-basic-suite-master

2022-08-01 05:29 UTC, erav commented
succeeded on he-basic-suite-master with:
`vdsm-tool ovn-config fd00:1234:5678:900:0:0:0:75 fd8f:1391:3a82:201:0:0:c0a8:c903 ost-he-basic-suite-master-host-0.lago.local`

2022-08-01 11:48 UTC, didib approved these changes

2022-08-01 12:11 UTC, didib commented
Taking back my approval. Not fully clear why we need this patch. When running `hosted-engine --deploy`, `he_host_name` should include the answer to `Please provide the hostname of this host on the management network`. When running the role directly, the caller should supply a correct `he_host_name`. What's missing?

2022-08-01 13:20 UTC, erav commented
/ost he-basic-suite-master

2022-08-01 13:29 UTC, erav commented
/ost he-basic-suite-master

2022-08-01 15:54 UTC, erav commented
succeeded with `he_host_address` on he-basic-suite-master with:
`vdsm-tool ovn-config fd00:1234:5678:900:0:0:0:38 fd8f:1391:3a82:214:0:0:c0a8:d603 ost-he-basic-suite-master-host-0.lago.local`

2022-08-02 12:22 UTC, michalskrivanek commented
from roles/hosted_engine_setup/tasks/fetch_host_ip.yml :
```
- name: Set hostname variable if not defined
  ansible.builtin.set_fact:
    he_host_name: "{{ host_full_name.stdout_lines[0] }}"
  when: he_host_name is none
- name: Define host address variable if not defined
  ansible.builtin.set_fact:
    he_host_address: "{{ host_full_name.stdout_lines[0] }}"
  when: he_host_address is none
```

2022-08-02 12:22 UTC, michalskrivanek requested changes
indeed we should use he_host_name

2022-08-02 12:42 UTC, didib commented
> indeed we should use he_host_name

No.

We discussed this thoroughly in private. Summary:

- The README is correct, re he_host_name and he_host_address.
- Both default to $(hostname -f), but have different meanings - he_host_name is the "Name" (as shown e.g. in the engine UI) and he_host_address is the "address" (IP Address or any resolvable name).

2022-08-02 12:44 UTC, michalskrivanek commented
yes, we just arrived to the same conclusion with Jiri Macku on QE setups

2022-08-02 12:46 UTC, didib approved these changes

2022-08-02 12:47 UTC, michalskrivanek commented
I would try to clarify README.md then, because it is confusing and misleading:
```
he_host_name | $(hostname -f) | name used by the engine for the first host
he_host_address | $(hostname -f) | address used by the engine for the first host
```

2022-08-02 12:54 UTC, didib commented
> I would try to clarify README.md then, because it is confusing and misleading:
> 
> ```
> he_host_name | $(hostname -f) | name used by the engine for the first host
> he_host_address | $(hostname -f) | address used by the engine for the first host
> ```

Yes, that was also the claim of @mburman5 . Patches are welcome. I personally found "Host Address" misleading also on the engine side, unrelated to this role and before it existed. I personally think that this is worth of its own bug, perhaps both doc and code bugs, and that the texts should be reviewed by doc writers and not (only) developers...

2022-08-02 12:56 UTC, mwperina commented
Added additional commit to make description of he_host_name and he_host_address clear

2022-08-02 13:06 UTC, didib commented
> Added additional commit to make description of he_host_name and he_host_address clear

Thanks. Much better.

2022-08-02 13:10 UTC, michalskrivanek commented on changelogs/fragments/568-he-setup-configure-ovn-with-he-host-fqdn.yml
> +  - During he_setup, configure ovn with he__host_address (https://github.com/oVirt/ovirt-ansible-collection/pull/568).
__ typo

2022-08-02 13:37 UTC, merged