Add default_route usage to the ovirt_network module
oVirt/ovirt-ansible-collection pull request #647
Opened 2022-12-07 15:49 UTC by ilush

Currently, it is possible to configure default_route usage through web-UI or API, but not through ansible.

2023-01-02 11:12 UTC, mwperina requested changes
Could you please add changelog fragment documenting this change?

Other than that it looks good to me.

2023-01-18 09:22 UTC, mwperina approved these changes

2023-01-18 09:50 UTC, mnecas requested changes
Please add the `default_route` to the `DOCUMENTATION`

2023-01-18 12:23 UTC, mnecas approved these changes
LGTM

2023-01-18 12:23 UTC, merged