ovirt_host: Add refresh
oVirt/ovirt-ansible-collection pull request #673
Opened 2023-01-30 11:15 UTC by mnecas

Fixes https://github.com/oVirt/ovirt-ansible-collection/discussions/672

2023-01-30 11:40 UTC, mwperina requested changes
Please add changelog

2023-01-30 11:40 UTC, mwperina commented on plugins/modules/ovirt_host.py
> +            'refresh'
`refreshed` to align with other states?

2023-01-30 11:54 UTC, mnecas commented
The CI fails on some ansible-lint pip error

2023-02-14 13:15 UTC, mwperina approved these changes
+1

2023-02-14 13:16 UTC, merged